using System;
using System.Security.Cryptography;
using System.Text;

[NodePath("Actions/Security")]
[FriendlyName("Generate MD5 Hash", "Generates an MD5 hash string from a key.")]
[NodeHelp("http://www.uscript.net/docs/index.php?title=Node_Reference_Guide")]
[NodeCopyright("Copyright 2011 by Detox Studios LLC")]
[NodeAuthor("Detox Studios LLC", "http://www.detoxstudios.com")]
[NodeToolTip("Generates an MD5 hash string from a key.")]
public class uScriptAct_GenerateMD5Hash : uScriptLogic
{
	public bool Out
	{
		get
		{
			return true;
		}
	}

	public void In([FriendlyName("Key", "The string to be used to generate the hash from.")] string Key, [FriendlyName("MD5 Hash", "The MD5 Hash generated by the Key.")] out string Hash)
	{
		if (Key != string.Empty)
		{
			UTF8Encoding uTF8Encoding = new UTF8Encoding();
			byte[] bytes = uTF8Encoding.GetBytes(Key);
			MD5CryptoServiceProvider mD5CryptoServiceProvider = new MD5CryptoServiceProvider();
			byte[] array = mD5CryptoServiceProvider.ComputeHash(bytes);
			string text = string.Empty;
			for (int i = 0; i < array.Length; i++)
			{
				text += Convert.ToString(array[i], 16).PadLeft(2, '0');
			}
			Hash = text.PadLeft(32, '0');
		}
		else
		{
			uScriptDebug.Log("[Generate MD5 Hash] The Key provided was empty, returning an empty string for the MD5 Hash.", uScriptDebug.Type.Warning);
			Hash = string.Empty;
		}
	}
}
